services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17101
      POSTGRES_DB: gopa
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gopa-network

volumes:
  postgres_data:

networks:
  gopa-network:
    driver: bridge
